"use client";
import { useEffect,useMemo,useState } from "react";
import { supabase } from "../../lib/supabase";

function money(v){return new Intl.NumberFormat("th-TH",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v||0));}
function fmtDate(v){return new Date(v).toLocaleDateString("th-TH",{timeZone:"Asia/Bangkok"});}
function startOf(mode){const now=new Date();const d=new Date(now);if(mode==="week"){d.setDate(now.getDate()-6);d.setHours(0,0,0,0);}else if(mode==="month"){d.setDate(1);d.setHours(0,0,0,0);}else if(mode==="year"){d.setMonth(0,1);d.setHours(0,0,0,0);}else return null;return d;}
export default function FinanceReportsPage(){
 const[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[range,setRange]=useState("month"),[from,setFrom]=useState(""),[to,setTo]=useState(""),[error,setError]=useState("");
 async function load(){setLoading(true);setError("");const{data,error}=await supabase.from("finance_transactions").select("*").eq("status","confirmed").order("transaction_date",{ascending:false});if(error)setError(error.message);else setRows(data||[]);setLoading(false);}
 useEffect(()=>{load();},[]);
 const filtered=useMemo(()=>rows.filter(x=>{const d=new Date(x.transaction_date);if(range!=="custom"){const s=startOf(range);return !s||d>=s;}if(from&&d<new Date(from+"T00:00:00+07:00"))return false;if(to&&d>new Date(to+"T23:59:59+07:00"))return false;return true;}),[rows,range,from,to]);
 const summary=useMemo(()=>{const income=filtered.filter(x=>x.direction==="income").reduce((s,x)=>s+Number(x.amount||0),0);const expense=filtered.filter(x=>x.direction==="expense").reduce((s,x)=>s+Number(x.amount||0),0);return{income,expense,net:income-expense};},[filtered]);
 const categories=useMemo(()=>{const m={};filtered.forEach(x=>{const k=x.category||"อื่น ๆ";m[k]??={category:k,income:0,expense:0,count:0};m[k][x.direction]+=Number(x.amount||0);m[k].count++;});return Object.values(m).sort((a,b)=>(b.income+b.expense)-(a.income+a.expense));},[filtered]);
 const projects=useMemo(()=>{const m={};filtered.forEach(x=>{const k=x.project_name?.trim()||"ไม่ระบุงาน";m[k]??={project:k,income:0,expense:0};m[k][x.direction]+=Number(x.amount||0);});return Object.values(m).map(x=>({...x,profit:x.income-x.expense})).sort((a,b)=>b.profit-a.profit);},[filtered]);
 const sources=useMemo(()=>{const m={};filtered.forEach(x=>m[x.source]=(m[x.source]||0)+1);return m;},[filtered]);
 function exportCsv(){const header=["วันที่","ประเภท","จำนวน","หมวดหมู่","Job","รายละเอียด","แหล่ง","คู่ค้า","ธนาคาร","เลขอ้างอิง"];const body=filtered.map(x=>[fmtDate(x.transaction_date),x.direction==="income"?"รายรับ":"รายจ่าย",Number(x.amount||0),x.category||"",x.project_name||"",x.description||"",x.source||"",x.counterparty||"",x.bank_name||"",x.reference_no||""]);const csv=[header,...body].map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n");const blob=new Blob(["\uFEFF"+csv],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`finance-report-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href);}
 const box={background:"white",border:"1px solid #e5e7eb",borderRadius:12,padding:16};const th={textAlign:"left",padding:10,borderBottom:"1px solid #e5e7eb"};const td={padding:10,borderBottom:"1px solid #f3f4f6"};const input={padding:9,border:"1px solid #d1d5db",borderRadius:7};
 return <main style={{minHeight:"100vh",background:"#f3f4f6",padding:24,color:"#111827"}}><div style={{maxWidth:1400,margin:"auto"}}>
  <div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap",alignItems:"center"}}><div><h1 style={{marginBottom:4}}>รายงานการเงิน</h1><p style={{marginTop:0,color:"#6b7280"}}>สรุปรายวัน รายสัปดาห์ รายเดือน และกำไรต่อ Job จาก LINE + Gallery + รายการกรอกเอง</p></div><div style={{display:"flex",gap:8}}><a href="/finance">← การเงิน</a><button onClick={exportCsv}>ส่งออก CSV</button></div></div>
  <div style={{display:"flex",gap:8,flexWrap:"wrap",margin:"16px 0"}}><select value={range} onChange={e=>setRange(e.target.value)} style={input}><option value="week">7 วันล่าสุด</option><option value="month">เดือนนี้</option><option value="year">ปีนี้</option><option value="all">ทั้งหมด</option><option value="custom">กำหนดช่วงเอง</option></select>{range==="custom"&&<><input type="date" value={from} onChange={e=>setFrom(e.target.value)} style={input}/><input type="date" value={to} onChange={e=>setTo(e.target.value)} style={input}/></>}<button onClick={load}>รีเฟรช</button></div>
  {error&&<p style={{color:"#b91c1c"}}>{error}</p>}
  <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:12,marginBottom:16}}><Stat label="รายรับ" value={`฿${money(summary.income)}`}/><Stat label="รายจ่าย" value={`฿${money(summary.expense)}`}/><Stat label="สุทธิ" value={`฿${money(summary.net)}`}/><Stat label="จำนวนรายการ" value={`${filtered.length} รายการ`}/></div>
  <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(320px,1fr))",gap:16}}><section style={box}><h2>แยกตามหมวดหมู่</h2><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr><th style={th}>หมวด</th><th style={th}>รายรับ</th><th style={th}>รายจ่าย</th></tr></thead><tbody>{categories.map(x=><tr key={x.category}><td style={td}>{x.category} ({x.count})</td><td style={td}>฿{money(x.income)}</td><td style={td}>฿{money(x.expense)}</td></tr>)}</tbody></table></section><section style={box}><h2>แหล่งข้อมูล</h2><p>LINE: {sources.line||0} รายการ</p><p>Gallery: {sources.gallery||0} รายการ</p><p>กรอกเอง: {sources.manual||0} รายการ</p><p>Invoice/Receipt: {(sources.invoice||0)+(sources.receipt||0)} รายการ</p></section></div>
  <section style={{...box,marginTop:16}}><h2>กำไร / ขาดทุน ต่อ Job</h2><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:650}}><thead><tr><th style={th}>Job</th><th style={th}>รายรับ</th><th style={th}>รายจ่าย</th><th style={th}>กำไร</th></tr></thead><tbody>{projects.map(x=><tr key={x.project}><td style={td}>{x.project}</td><td style={td}>฿{money(x.income)}</td><td style={td}>฿{money(x.expense)}</td><td style={{...td,fontWeight:800,color:x.profit>=0?"#15803d":"#b91c1c"}}>฿{money(x.profit)}</td></tr>)}</tbody></table></div></section>
  <section style={{...box,marginTop:16}}><h2>รายการในช่วงที่เลือก</h2>{loading?<p>กำลังโหลด...</p>:<div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:900}}><thead><tr><th style={th}>วันที่</th><th style={th}>ประเภท</th><th style={th}>จำนวน</th><th style={th}>หมวด</th><th style={th}>Job</th><th style={th}>แหล่ง</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td style={td}>{fmtDate(x.transaction_date)}</td><td style={td}>{x.direction==="income"?"รายรับ":"รายจ่าย"}</td><td style={td}>฿{money(x.amount)}</td><td style={td}>{x.category}</td><td style={td}>{x.project_name||"-"}</td><td style={td}>{x.source}</td></tr>)}</tbody></table></div>}</section>
 </div></main>;
}
function Stat({label,value}){return <div style={{background:"white",border:"1px solid #e5e7eb",borderRadius:12,padding:16}}><div style={{fontSize:13,color:"#6b7280"}}>{label}</div><div style={{fontSize:26,fontWeight:800,marginTop:4}}>{value}</div></div>}
