"use client";
import {useEffect,useMemo,useState} from "react";
import {supabase} from "../../lib/supabase";

function money(v){return new Intl.NumberFormat("th-TH",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v||0));}
function fmtDate(v){return new Date(v).toLocaleDateString("th-TH",{timeZone:"Asia/Bangkok"});}
function startOf(mode){const now=new Date(),d=new Date(now);if(mode==="week"){d.setDate(now.getDate()-6);d.setHours(0,0,0,0);}else if(mode==="month"){d.setDate(1);d.setHours(0,0,0,0);}else if(mode==="year"){d.setMonth(0,1);d.setHours(0,0,0,0);}else return null;return d;}
const box={background:"white",border:"1px solid #e5e7eb",borderRadius:14,padding:16};
const input={padding:"10px 12px",border:"1px solid #d1d5db",borderRadius:9,background:"white"};
const th={textAlign:"left",padding:10,borderBottom:"1px solid #e5e7eb",fontSize:12,color:"#64748b",whiteSpace:"nowrap"};
const td={padding:10,borderBottom:"1px solid #f1f5f9",fontSize:13};

export default function FinanceReportsPage(){
 const[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[range,setRange]=useState("month"),[from,setFrom]=useState(""),[to,setTo]=useState(""),[error,setError]=useState(""),[type,setType]=useState("all");
 async function load(){setLoading(true);setError("");const{data,error}=await supabase.from("finance_transactions").select("*").eq("status","confirmed").order("transaction_date",{ascending:false});if(error)setError(error.message);else setRows(data||[]);setLoading(false);}
 useEffect(()=>{load();},[]);
 const filtered=useMemo(()=>rows.filter(x=>{const d=new Date(x.transaction_date);if(type!=="all"&&x.direction!==type)return false;if(range!=="custom"){const s=startOf(range);return !s||d>=s;}if(from&&d<new Date(from+"T00:00:00+07:00"))return false;if(to&&d>new Date(to+"T23:59:59+07:00"))return false;return true;}),[rows,range,from,to,type]);
 const summary=useMemo(()=>{const income=filtered.filter(x=>x.direction==="income").reduce((s,x)=>s+Number(x.amount||0),0),expense=filtered.filter(x=>x.direction==="expense").reduce((s,x)=>s+Number(x.amount||0),0);return{income,expense,net:income-expense};},[filtered]);
 const categories=useMemo(()=>{const m={};filtered.forEach(x=>{const k=x.category||"อื่น ๆ";m[k]??={category:k,income:0,expense:0,count:0};m[k][x.direction]+=Number(x.amount||0);m[k].count++;});return Object.values(m).sort((a,b)=>(b.income+b.expense)-(a.income+a.expense));},[filtered]);
 const projects=useMemo(()=>{const m={};filtered.forEach(x=>{const k=x.project_name?.trim()||"ไม่ระบุงาน";m[k]??={project:k,income:0,expense:0};m[k][x.direction]+=Number(x.amount||0);});return Object.values(m).map(x=>({...x,profit:x.income-x.expense})).sort((a,b)=>b.profit-a.profit);},[filtered]);
 const maxCategory=Math.max(1,...categories.map(x=>x.income+x.expense));
 function exportCsv(){const header=["วันที่","ประเภท","จำนวน","หมวดหมู่","Job","รายละเอียด","แหล่ง","คู่ค้า","ธนาคาร","เลขอ้างอิง"],body=filtered.map(x=>[fmtDate(x.transaction_date),x.direction==="income"?"รายรับ":"รายจ่าย",Number(x.amount||0),x.category||"",x.project_name||"",x.description||"",x.source||"",x.counterparty||"",x.bank_name||"",x.reference_no||""]);const csv=[header,...body].map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n"),blob=new Blob(["\uFEFF"+csv],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`finance-report-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href);}
 return <main style={{minHeight:"100vh",background:"#f4f6f8",padding:"18px 12px 80px",color:"#0f172a"}}><div style={{maxWidth:1280,margin:"auto"}}>
  <div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap",alignItems:"center"}}><div><h1 style={{margin:"0 0 4px"}}>📊 รายงานการเงิน</h1><p style={{margin:0,color:"#64748b"}}>รายรับสีน้ำเงิน • รายจ่ายสีแดง • แยกตามหมวดหมู่และ Job</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><a href="/finance" style={{padding:10,textDecoration:"none"}}>← การเงิน</a><a href="/finance/categories" style={{padding:10,textDecoration:"none"}}>🏷️ หมวดหมู่</a><button onClick={exportCsv}>ส่งออก CSV</button><button onClick={()=>window.print()}>พิมพ์ / PDF</button></div></div>
  <div style={{display:"flex",gap:8,flexWrap:"wrap",margin:"16px 0"}}><select value={range} onChange={e=>setRange(e.target.value)} style={input}><option value="week">7 วันล่าสุด</option><option value="month">เดือนนี้</option><option value="year">ปีนี้</option><option value="all">ทั้งหมด</option><option value="custom">กำหนดช่วงเอง</option></select><select value={type} onChange={e=>setType(e.target.value)} style={input}><option value="all">ทั้งหมด</option><option value="income">รายรับ</option><option value="expense">รายจ่าย</option></select>{range==="custom"&&<><input type="date" value={from} onChange={e=>setFrom(e.target.value)} style={input}/><input type="date" value={to} onChange={e=>setTo(e.target.value)} style={input}/></>}<button onClick={load}>รีเฟรช</button></div>
  {error&&<div style={{color:"#b91c1c",background:"#fef2f2",padding:12,borderRadius:10}}>{error}</div>}
  <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12,marginBottom:16}}><Stat label="รายรับ" value={`฿${money(summary.income)}`} color="#0b6cff" bg="#eff6ff"/><Stat label="รายจ่าย" value={`฿${money(summary.expense)}`} color="#e11d48" bg="#fff1f2"/><Stat label="ยอดคงเหลือ" value={`฿${money(summary.net)}`} color={summary.net>=0?"#15803d":"#b91c1c"} bg="#f0fdf4"/><Stat label="จำนวนรายการ" value={`${filtered.length} รายการ`} color="#334155" bg="#f8fafc"/></div>
  <section style={box}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:8,flexWrap:"wrap"}}><h2 style={{margin:0}}>สรุปตามหมวดหมู่</h2><a href="/finance/categories">ดูรายละเอียดทั้งหมด →</a></div>{categories.length===0?<p style={{color:"#64748b"}}>ยังไม่มีข้อมูลในช่วงที่เลือก</p>:<div style={{marginTop:14,display:"grid",gap:12}}>{categories.map(x=>{const total=x.income+x.expense,pct=Math.max(2,total/maxCategory*100);return <a key={x.category} href={`/finance/categories?category=${encodeURIComponent(x.category)}`} style={{textDecoration:"none",color:"inherit",display:"grid",gridTemplateColumns:"minmax(140px,1.2fr) 2fr minmax(120px,.8fr)",gap:12,alignItems:"center"}}><div><b>{x.category}</b><div style={{fontSize:12,color:"#64748b"}}>{x.count} รายการ</div></div><div style={{height:12,background:"#eef2f7",borderRadius:999,overflow:"hidden"}}><div style={{height:"100%",width:`${pct}%`,background:x.income>=x.expense?"#0b6cff":"#e11d48",borderRadius:999}}/></div><div style={{textAlign:"right",fontWeight:800,color:x.income>=x.expense?"#0b6cff":"#e11d48"}}>฿{money(total)}</div></a>})}</div>}</section>
  <section style={{...box,marginTop:16}}><h2 style={{marginTop:0}}>กำไร / ขาดทุน ต่อ Job</h2><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:650}}><thead><tr><th style={th}>Job</th><th style={th}>รายรับ</th><th style={th}>รายจ่าย</th><th style={th}>กำไร</th></tr></thead><tbody>{projects.map(x=><tr key={x.project}><td style={td}>{x.project}</td><td style={{...td,color:"#0b6cff",fontWeight:700}}>฿{money(x.income)}</td><td style={{...td,color:"#e11d48",fontWeight:700}}>฿{money(x.expense)}</td><td style={{...td,fontWeight:900,color:x.profit>=0?"#15803d":"#b91c1c"}}>฿{money(x.profit)}</td></tr>)}</tbody></table></div></section>
  <section style={{...box,marginTop:16}}><h2 style={{marginTop:0}}>รายการในช่วงที่เลือก</h2>{loading?<p>กำลังโหลด...</p>:<div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:850}}><thead><tr><th style={th}>วันที่</th><th style={th}>ประเภท</th><th style={th}>จำนวน</th><th style={th}>หมวด</th><th style={th}>Job</th><th style={th}>รายละเอียด</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td style={td}>{fmtDate(x.transaction_date)}</td><td style={{...td,color:x.direction==="income"?"#0b6cff":"#e11d48",fontWeight:800}}>{x.direction==="income"?"รายรับ":"รายจ่าย"}</td><td style={{...td,fontWeight:800}}>฿{money(x.amount)}</td><td style={td}>{x.category||"อื่น ๆ"}</td><td style={td}>{x.project_name||"-"}</td><td style={td}>{x.description||"-"}</td></tr>)}</tbody></table></div>}</section>
 </div><style jsx global>{`@media print{button,a[href="/finance"],a[href="/finance/categories"]{display:none!important}body{background:white!important}}@media(max-width:700px){main{padding-left:8px!important;padding-right:8px!important}}`}</style></main>;
}
function Stat({label,value,color,bg}){return <div style={{background:bg,border:"1px solid #e5e7eb",borderRadius:14,padding:16}}><div style={{fontSize:13,color:"#64748b"}}>{label}</div><div style={{fontSize:25,fontWeight:900,marginTop:4,color}}>{value}</div></div>}
