import {extractThaiSlipDate,inferSlipDirection} from './slipFieldFixes';
let workerPromise;
async function prep(file,top=0,bottom=1){const url=URL.createObjectURL(file);try{const img=await new Promise((resolve,reject)=>{const x=new Image();x.onload=()=>resolve(x);x.onerror=()=>reject(new Error('เปิดรูปสลิปไม่สำเร็จ'));x.src=url;});const y=Math.floor(img.naturalHeight*top),h=Math.max(1,Math.floor(img.naturalHeight*bottom)-y),scale=Math.max(1.8,Math.min(3,2200/Math.max(1,img.naturalWidth)));const c=document.createElement('canvas');c.width=Math.round(img.naturalWidth*scale);c.height=Math.round(h*scale);const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,0,y,img.naturalWidth,h,0,0,c.width,c.height);const im=ctx.getImageData(0,0,c.width,c.height),d=im.data;for(let i=0;i<d.length;i+=4){const g=Math.round(.299*d[i]+.587*d[i+1]+.114*d[i+2]);const v=g>220?255:g<64?0:Math.max(0,Math.min(255,Math.round((g-128)*1.5+128)));d[i]=d[i+1]=d[i+2]=v;}ctx.putImageData(im,0,0);return await new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('เตรียมรูป OCR ไม่สำเร็จ')),'image/jpeg',.96));}finally{URL.revokeObjectURL(url);}}
const clean=s=>String(s||'').replace(/[๐-๙]/g,c=>String('๐๑๒๓๔๕๖๗๘๙'.indexOf(c))).replace(/[，]/g,',').replace(/[：]/g,':').replace(/[‐‑‒–—−]/g,'-');
const label=/(จำนวนเงิน|ยอดเงิน|ยอดโอน|ยอดชำระ|amount|total)/i;
const excluded=/(วันที่|date|เวลา|time|ค่าธรรมเนียม|fee|อ้างอิง|reference|เลขบัญชี|account|\b25\d{2}\b|\d{1,2}\s*:\s*\d{2})/i;
function candidates(line){const out=[];const re=/(^|[^\dA-Za-z])((?:\d{1,3}(?:,\d{3})+|\d{1,8})(?:\.\d{2})?)(?![\dA-Za-z.])/g;let m;while((m=re.exec(line))){const n=Number(m[2].replace(/,/g,''));if(Number.isFinite(n)&&n>0&&n<100000000)out.push(n);}return out;}
function findAmount(text){const lines=clean(text).split(/\r?\n/).map(x=>x.trim()).filter(Boolean);for(let i=0;i<lines.length;i++){if(!label.test(lines[i]))continue;for(const line of [lines[i].replace(label,''),lines[i+1]||'',lines[i+2]||'']){if(excluded.test(line))continue;const values=candidates(line);if(values.length===1)return values[0];}}const found=[];for(const line of lines){if(excluded.test(line))continue;for(const n of candidates(line.match(/(?:^|\s)(?:\d{1,3}(?:,\d{3})+|\d{1,8})\.\d{2}(?:\s|$)/)?.[0]||''))found.push(n);}return found.length&&found.every(n=>n===found[0])?found[0]:null;}
function parse(text=''){const t=clean(text),amount=findAmount(t),transaction_date=extractThaiSlipDate(t),direction=inferSlipDirection(t);const bank=t.match(/กรุงไทย|กสิกรไทย|ไทยพาณิชย์|กรุงเทพ|กรุงศรี|ทหารไทยธนชาต|ออมสิน|ธ\.ก\.ส\.|Krungthai|Kasikorn|SCB|Bangkok Bank|Krungsri|TTB/i);const ref=t.match(/(?:เลขที่รายการ|เลขอ้างอิง|รหัสอ้างอิง|Reference|Ref\.?|Transaction ID)\s*[:#]?\s*([A-Za-z0-9-]{8,})/i);return{amount:amount==null?'':String(amount),transaction_date,direction,bank_name:bank?.[0]||'',reference_no:ref?.[1]||'',raw_text:t};}
export async function readSlipLocally(file,onProgress=()=>{}){if(!file||!file.type.startsWith('image/'))throw new Error('กรุณาเลือกรูปภาพสลิป');if(file.size>15*1024*1024)throw new Error('รูปภาพต้องไม่เกิน 15 MB');if(!workerPromise)workerPromise=import('tesseract.js').then(({createWorker})=>createWorker('tha+eng',1,{logger:m=>{if(m.status==='recognizing text')onProgress(Math.min(70,Math.round(m.progress*70)));}})).catch(e=>{workerPromise=null;throw e;});const worker=await workerPromise;let text='';const passes=[[0,1,'3'],[.2,.98,'6'],[.55,.99,'6']];try{for(let i=0;i<passes.length;i++){const current=parse(text);if(i>0&&current.amount&&current.transaction_date&&current.direction)break;onProgress(i===0?5:i===1?74:88);const img=await prep(file,passes[i][0],passes[i][1]);await worker.setParameters({tessedit_pageseg_mode:passes[i][2],preserve_interword_spaces:'1',tessedit_char_whitelist:''});const r=await worker.recognize(img);text+=(text?'\n':'')+(r.data.text||'');}}finally{await worker.setParameters({tessedit_pageseg_mode:'3',preserve_interword_spaces:'0',tessedit_char_whitelist:''});}onProgress(100);return{text,confidence:null,fields:parse(text)};}
export function parseSlipText(text){return parse(text);}
