import {extractThaiSlipDate,inferSlipDirection,extractSlipParties} from './slipFieldFixes';
let workerPromise;
const clean=s=>String(s||'').replace(/[๐-๙]/g,c=>String('๐๑๒๓๔๕๖๗๘๙'.indexOf(c))).replace(/[，]/g,',').replace(/[：]/g,':').replace(/[‐‑‒–—−]/g,'-');
const split=text=>clean(text).split(/\n\s*-{2,}\s*OCR_PASS\s*-{2,}\s*\n/i).filter(Boolean);
const money=/(จำนวนเงิน|ยอดเงิน|ยอดโอน|ยอดชำระ|amount|total)/i;
const fee=/(ค่าธรรมเนียม|fee)/i;
const excluded=/(วันที่|date|เวลา|time|อ้างอิง|reference|เลขบัญชี|account|customer\s*no|ref\s*no|หมายเลขผู้ใช้ไฟฟ้า|รหัสร้านค้า|รหัสธุรกรรม|ยอดค้างชำระ)/i;
function tokens(s){const out=[];const re=/(?:^|[^\dA-Za-z])((?:\d{1,3}(?:,\d{3})+|\d{1,8})(?:\.\d{1,2})?)(?![\dA-Za-z.,])/g;let m;while((m=re.exec(clean(s)))){const n=Number(m[1].replace(/,/g,''));if(n>0&&n<100000000)out.push(n);}return out;}
function amountCandidates(text){const lines=clean(text).split(/\r?\n/).map(x=>x.trim()).filter(Boolean),out=[];for(let i=0;i<lines.length;i++){if(!money.test(lines[i])||fee.test(lines[i])||excluded.test(lines[i]))continue;for(const [j,line] of [lines[i].replace(money,''),lines[i+1]||''].entries()){if(fee.test(line)||excluded.test(line))continue;const vals=tokens(line);if(vals.length===1)out.push({value:vals[0],weight:j===0?5:3});if(vals.length)break;}}for(const line of lines){if(fee.test(line)||excluded.test(line))continue;const m=line.match(/(?:^|\s)((?:\d{1,3}(?:,\d{3})+|\d{1,8})\.\d{2})\s*(?:บาท|baht|฿)/i);if(m)out.push({value:Number(m[1].replace(/,/g,'')),weight:2});}return out;}
function chooseAmount(text){const votes=new Map();for(const pass of split(text)){const seen=new Set();for(const c of amountCandidates(pass)){if(seen.has(c.value))continue;seen.add(c.value);votes.set(c.value,(votes.get(c.value)||0)+c.weight);}}if(!votes.size)return null;const ranked=[...votes].sort((a,b)=>b[1]-a[1]);if(ranked.length>1&&ranked[0][1]===ranked[1][1])return null;return ranked[0][0];}
function bankFrom(t){return clean(t).match(/กรุงไทย|กสิกรไทย|ไทยพาณิชย์|กรุงเทพ|กรุงศรี|ทหารไทยธนชาต|ออมสิน|ธ\.ก\.ส\.|Krungthai|Kasikorn|SCB|Bangkok Bank|Krungsri|TTB/i)?.[0]||'';}
function referenceFrom(t){const m=clean(t).match(/(?:รหัสอ้างอิง|เลขอ้างอิง|Reference|Ref\.?|Transaction ID|เลขที่รายการ)\s*[:#]?\s*([A-Za-z0-9-]{8,})/i);return m?.[1]||'';}
function mode(values){const c=new Map();for(const v of values.filter(Boolean))c.set(v,(c.get(v)||0)+1);return [...c].sort((a,b)=>b[1]-a[1])[0]?.[0]||'';}
function details(text){const lines=clean(text).split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const memo=[];for(let i=0;i<lines.length;i++){const m=lines[i].match(/(?:บันทึกช่วยจำ|หมายเหตุ|memo|note)\s*[:：]?\s*(.*)$/i);if(m){const v=m[1]||lines[i+1]||'';if(v&&!/^(?:จำนวนเงิน|ค่าธรรมเนียม|วันที่|เลขอ้างอิง)/.test(v))memo.push(v);}}const parties=extractSlipParties(text);let counterparty='';const direction=inferSlipDirection(text);const section=direction==='expense'?parties.to:direction==='income'?parties.from:'';counterparty=section.split(/\s*\|\s*/).find(x=>x&&!/^(?:กรุงไทย|กสิกรไทย|ไทยพาณิชย์|กรุงเทพ|กรุงศรี|\d|xxx)/i.test(x))||'';if(!counterparty){counterparty=lines.find(x=>/POWELL INTERNATIONAL|การไฟฟ้าส่วนภูมิภาค|โตโยต้าลีสซิ่ง|ทรูมูฟ|true\s*move/i.test(x))||'';}return{counterparty,description:mode(memo)};}
export function parseSlipText(text=''){const t=clean(text),passes=split(t),amount=chooseAmount(t),transaction_date=extractThaiSlipDate(t),direction=inferSlipDirection(t),d=details(t);return{amount:amount==null?'':String(amount),transaction_date,direction,bank_name:mode(passes.map(bankFrom))||bankFrom(t),reference_no:mode(passes.map(referenceFrom))||referenceFrom(t),...d,raw_text:t};}
async function prep(file,top=0,bottom=1,variant='contrast'){const url=URL.createObjectURL(file);try{const img=await new Promise((resolve,reject)=>{const x=new Image();x.onload=()=>resolve(x);x.onerror=()=>reject(new Error('เปิดรูปสลิปไม่สำเร็จ'));x.src=url;});const y=Math.floor(img.naturalHeight*top),h=Math.max(1,Math.floor(img.naturalHeight*bottom)-y),scale=Math.max(1.8,Math.min(3,2200/Math.max(1,img.naturalWidth)));const c=document.createElement('canvas');c.width=Math.round(img.naturalWidth*scale);c.height=Math.round(h*scale);const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,0,y,img.naturalWidth,h,0,0,c.width,c.height);if(variant!=='original'){const im=ctx.getImageData(0,0,c.width,c.height),d=im.data;for(let i=0;i<d.length;i+=4){const g=Math.round(.299*d[i]+.587*d[i+1]+.114*d[i+2]);const v=variant==='threshold'?(g>175?255:0):(g>225?255:g<60?0:Math.max(0,Math.min(255,Math.round((g-128)*1.55+128))));d[i]=d[i+1]=d[i+2]=v;}ctx.putImageData(im,0,0);}return await new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('เตรียมรูป OCR ไม่สำเร็จ')),'image/jpeg',.96));}finally{URL.revokeObjectURL(url);}}
export async function readSlipLocally(file,onProgress=()=>{}){if(!file||!file.type.startsWith('image/'))throw new Error('กรุณาเลือกรูปภาพสลิป');if(file.size>15*1024*1024)throw new Error('รูปภาพต้องไม่เกิน 15 MB');if(!workerPromise)workerPromise=import('tesseract.js').then(({createWorker})=>createWorker('tha+eng',1,{logger:m=>{if(m.status==='recognizing text')onProgress(Math.min(68,Math.round(m.progress*68)));}})).catch(e=>{workerPromise=null;throw e;});const worker=await workerPromise;let text='';const passes=[[0,1,'3','contrast'],[0,1,'6','original'],[.18,.99,'6','contrast'],[.42,.99,'6','threshold']];try{for(let i=0;i<passes.length;i++){onProgress([5,35,65,84][i]);const img=await prep(file,passes[i][0],passes[i][1],passes[i][3]);await worker.setParameters({tessedit_pageseg_mode:passes[i][2],preserve_interword_spaces:'1',tessedit_char_whitelist:''});const r=await worker.recognize(img);text+=(text?'\n---OCR_PASS---\n':'')+(r.data.text||'');}}finally{await worker.setParameters({tessedit_pageseg_mode:'3',preserve_interword_spaces:'0',tessedit_char_whitelist:''});}onProgress(100);return{text,confidence:null,fields:parseSlipText(text)};}
