const digits=s=>String(s||'').replace(/[๐-๙]/g,c=>String('๐๑๒๓๔๕๖๗๘๙'.indexOf(c)));
const clean=s=>digits(s).replace(/[：]/g,':').replace(/[‐‑‒–—−]/g,'-').replace(/[／]/g,'/').replace(/[\u200b-\u200d]/g,' ');
const normalize=s=>clean(s).toLowerCase().replace(/[^a-z0-9ก-๙]/g,'');
const splitPasses=text=>clean(text).split(/\n\s*-{2,}\s*OCR_PASS\s*-{2,}\s*\n/i).map(x=>x.trim()).filter(Boolean);
const num=s=>Number(String(s).replace(/[Oo]/g,'0').replace(/[Il|]/g,'1'));

function own(s){const n=normalize(s);const thanee=n.includes('ธานี')&&(n.includes('แอดเวอร์')||n.includes('แอดเวอ')||n.includes('แอด')||n.includes('ไทซิ่ง')||n.includes('ไทซ')||n.includes('advertis'));const owner=n.includes('ศิวนนท์')||n.includes('ศค้วนนท์')||n.includes('ศุภฐิติ')||n.includes('ศุภฐติ');return thanee||owner;}

function formatDate(d,m,y,{thaiShort=false}={}){d=num(d);m=num(m);y=num(y);if(y<100)y=thaiShort?2500+y:2000+y;if(y>2400)y-=543;if(y<2000||y>2100||m<1||m>12||d<1||d>31)return'';const x=new Date(Date.UTC(y,m-1,d));return x.getUTCFullYear()===y&&x.getUTCMonth()===m-1&&x.getUTCDate()===d?`${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`:'';}
const months={มค:1,กพ:2,มีค:3,เมย:4,เมษายน:4,พค:5,มิย:6,กค:7,สค:8,กย:9,ตค:10,พย:11,ธค:12,มกราคม:1,กุมภาพันธ์:2,มีนาคม:3,พฤษภาคม:5,มิถุนายน:6,กรกฎาคม:7,สิงหาคม:8,กันยายน:9,ตุลาคม:10,พฤศจิกายน:11,ธันวาคม:12};
function monthToken(s){const raw=clean(s).toLowerCase().replace(/[\s.·,]/g,'');if(months[raw])return months[raw];const stripped=raw.replace(/[ุูิีึืั็่้๊๋์ํ]/g,'');if(months[stripped])return months[stripped];if(/^ก.?ย/.test(raw))return 9;if(/^ส.?ค/.test(raw))return 8;if(/^ต.?ค/.test(raw))return 10;return 0;}
function dateFromOnePass(text=''){const s=clean(text);let m;const named=/([0-9OoIl|]{1,2})\s*([ก-๙.\s]{1,18}?)\s*([0-9OoIl|]{2,4})(?=\s|[-–]|\d{1,2}\s*:\s*\d{2}|น\.?|$)/gi;while((m=named.exec(s))){const month=monthToken(m[2]);if(month){const yy=String(m[3]).replace(/\D/g,'');const v=formatDate(m[1],month,m[3],{thaiShort:yy.length===2});if(v)return v;}}const numeric=/([0-9OoIl|]{1,2})\s*[\/\-.]\s*([0-9OoIl|]{1,2})\s*[\/\-.]\s*([0-9OoIl|]{2,4})(?!\d)/gi;while((m=numeric.exec(s))){const yy=String(m[3]).replace(/\D/g,'');let v=formatDate(m[1],m[2],m[3],{thaiShort:false});if(v)return v;if(yy.length===2){v=formatDate(m[1],m[2],m[3],{thaiShort:true});if(v)return v;}}return'';}
export function extractThaiSlipDate(text=''){const vals=splitPasses(text).map(dateFromOnePass).filter(Boolean);if(!vals.length)return dateFromOnePass(text);const counts=new Map();for(const v of vals)counts.set(v,(counts.get(v)||0)+1);return [...counts.entries()].sort((a,b)=>b[1]-a[1])[0][0];}

const sender=/^(?:จาก|จา[กค]|วาก|ผู้โอน|บัญชีผู้โอน|from|sender)(?=\s|:|：|[ก-๙A-Za-z]|$)/i;
const recipient=/^(?:ไปยัง|ไปยั[งง]|ผู้รับ|บัญชีผู้รับ|to|recipient)(?=\s|:|：|[ก-๙A-Za-z]|$)/i;
const stop=/^(?:จำนวนเงิน|จำนวน|ยอดเงิน|ยอดโอน|ยอดชำระ|ค่าธรรมเนียม|วันที่|วันที่ทำรายการ|วันท|เวลา|บันทึกช่วยจำ|หมายเหตุ|เลขที่รายการ|เลขอ้างอิง|รหัสอ้างอิง|reference|transaction|amount|total|fee|date|time|note|memo)(?=\s|:|：|[0-9]|$)/i;
function labelOf(line){return clean(line).replace(/^[^ก-๙A-Za-z]*/,'').trim();}
function stripMarker(line,re){return labelOf(line).replace(re,'').replace(/^\s*[:：-]?\s*/,'').trim();}
function sections(text=''){const lines=clean(text).split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const out={from:[],to:[]};let mode='';let buf=[];const flush=()=>{if(mode&&buf.length)out[mode].push(buf.join(' '));buf=[];};for(const raw of lines){const l=labelOf(raw);if(sender.test(l)){flush();mode='from';const rest=stripMarker(l,sender);if(rest)buf.push(rest);continue;}if(recipient.test(l)){flush();mode='to';const rest=stripMarker(l,recipient);if(rest)buf.push(rest);continue;}if(stop.test(l)){flush();mode='';continue;}if(mode)buf.push(raw);}flush();return out;}
function bankLine(s){const n=normalize(s);return /(?:กสิกรไทย|kasikorn|กรุงไทย|krungthai|ไทยพาณิชย์|scb|กรุงเทพ|bangkokbank|กรุงศรี|krungsri|ttb|ทหารไทย|ออมสิน|พร้อมเพย์|promptpay)/i.test(n);}
function kbankOrderDirection(text=''){const lines=clean(text).split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const whole=normalize(text);if(!(whole.includes('กสิกร')||whole.includes('kplus')||whole.includes('kbank')))return'';let end=lines.length;for(let i=0;i<lines.length;i++){if(/^(?:เลขที่รายการ|จำนวน|ค่าธรรมเนียม|reference|amount)/i.test(labelOf(lines[i]))){end=i;break;}}const ownIdx=[];for(let i=0;i<end;i++){const w=lines.slice(Math.max(0,i-1),Math.min(end,i+2)).join(' ');if(own(w))ownIdx.push(i);}if(!ownIdx.length)return'';const partyBanks=[];for(let i=0;i<end;i++)if(bankLine(lines[i]))partyBanks.push(i);if(!partyBanks.length)return'';for(const i of ownIdx){if(i<partyBanks[0])return'expense';if(i>partyBanks[0])return'income';}return'';}
function onePassDirection(text=''){const p=sections(text);const fromOwn=p.from.filter(own).length,toOwn=p.to.filter(own).length;if(fromOwn>0&&toOwn===0)return'expense';if(toOwn>0&&fromOwn===0)return'income';const kb=kbankOrderDirection(text);if(kb)return kb;const n=normalize(text);if((n.includes('จ่ายบิลสำเร็จ')||n.includes('ชำระบิลสำเร็จ'))&&own(text))return'expense';return'';}
export function extractSlipParties(text=''){const p=sections(text);return{from:p.from.join(' | '),to:p.to.join(' | ')};}
export function inferSlipDirection(text=''){const vals=splitPasses(text).map(onePassDirection).filter(Boolean);if(!vals.length)return onePassDirection(text);const income=vals.filter(x=>x==='income').length,expense=vals.filter(x=>x==='expense').length;if(income>expense)return'income';if(expense>income)return'expense';return'';}
