const clean=s=>String(s||'').replace(/[๐-๙]/g,c=>String('๐๑๒๓๔๕๖๗๘๙'.indexOf(c))).replace(/[：]/g,':').replace(/[‐‑‒–—−]/g,'-').replace(/[／]/g,'/').replace(/[\u200b-\u200d]/g,' ');
const norm=s=>clean(s).toLowerCase().replace(/[^a-z0-9ก-๙]/g,'');
const own=s=>{const n=norm(s);return (n.includes('ธานี')&&/แอดเว|ไทซ|advertis/.test(n))||n.includes('ศิวนนท์')||n.includes('ศุภฐิติ')||n.includes('ศุภฐติ');};
const sender=/^(?:จาก|จา[กค]|วาก|ผู้โอน|บัญชีผู้โอน|from|sender)(?=\s|:|[ก-๙A-Za-z]|$)/i;
const recipient=/^(?:ไปยัง|ไปยั[งง]|ผู้รับ|บัญชีผู้รับ|to|recipient)(?=\s|:|[ก-๙A-Za-z]|$)/i;
const stop=/^(?:จำนวนเงิน|จำนวน|ยอดเงิน|ยอดโอน|ยอดชำระ|ค่าธรรมเนียม|วันที่|วันท|เวลา|บันทึกช่วยจำ|หมายเหตุ|เลขอ้างอิง|รหัสอ้างอิง|เลขที่รายการ|รหัสร้านค้า|รหัสธุรกรรม|reference|transaction|amount|total|fee|date|time|note|memo)(?=\s|:|[0-9ก-๙]|$)/i;
const reset=/^(?:ocr_pass|โอนเงินสำเร็จ|ทำรายการสำเร็จ|จ่ายบิลสำเร็จ|krungthai|กรุงไทย|kasikorn|กสิกรไทย|scb|ไทยพาณิชย์|bangkok bank|ธนาคารกรุงเทพ|krungsri|กรุงศรี|ttb)(?:\s|$)/i;
const label=s=>clean(s).replace(/^[^ก-๙A-Za-z]*/,'').trim();
function sections(text){const out={from:[],to:[]};let mode='',buf=[];const flush=()=>{if(mode&&buf.length)out[mode].push(buf.join(' '));buf=[];};for(const raw of clean(text).split(/\r?\n/)){const l=label(raw);if(!l)continue;if(reset.test(l)){flush();mode='';continue;}if(sender.test(l)){flush();mode='from';const rest=l.replace(sender,'').replace(/^\s*[:：-]?\s*/,'');if(rest)buf.push(rest);continue;}if(recipient.test(l)){flush();mode='to';const rest=l.replace(recipient,'').replace(/^\s*[:：-]?\s*/,'');if(rest)buf.push(rest);continue;}if(stop.test(l)){flush();mode='';continue;}if(mode)buf.push(raw);}flush();return out;}
export function extractSlipParties(text=''){const p=sections(text);return{from:p.from.join(' | '),to:p.to.join(' | ')};}
export function inferSlipDirection(text='',accounts=[]){const p=sections(text);const match=s=>own(s)||accounts.some(a=>{const n=norm(a.name||'');const suffix=String(a.account_number||'').replace(/\D/g,'');return (n.length>=6&&norm(s).includes(n))||(suffix.length>=4&&new RegExp('(?:^|\\D)\\d{0,12}'+suffix+'(?:\\D|$)').test(clean(s).replace(/[xX*•\s-]/g,'')));});const from=p.from.some(match),to=p.to.some(match);if(from&&to)return'';if(from)return'expense';if(to)return'income';return'';}
const months={มค:1,กพ:2,มีค:3,เมย:4,พค:5,มิย:6,กค:7,สค:8,กย:9,ตค:10,พย:11,ธค:12};
function valid(d,m,y){d=Number(d);m=Number(m);y=Number(y);if(y>=2400)y-=543;if(y<100)y+=y>=40?1900:2000;if(y<2000||y>2100||m<1||m>12)return'';const x=new Date(Date.UTC(y,m-1,d));return x.getUTCFullYear()===y&&x.getUTCMonth()===m-1&&x.getUTCDate()===d?`${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`:'';}
export function extractThaiSlipDate(text=''){const s=clean(text);let m;const numeric=/(\d{1,2})\s*[\/\-.]\s*(\d{1,2})\s*[\/\-.]\s*(\d{2,4})(?!\d)/g;while((m=numeric.exec(s))){const v=valid(m[1],m[2],m[3]);if(v)return v;}const named=/(\d{1,2})\s*([ก-๙.\s]{2,24}?)\s*(\d{2,4})(?=\s|$|[-–]|\d{1,2}:)/g;while((m=named.exec(s))){const token=m[2].replace(/[\s.\u0e31-\u0e4e]/g,'');const month=months[token]||months[token.slice(0,2)];if(month){const v=valid(m[1],month,m[3]);if(v)return v;}}return'';}
